name: Publish VSCode Extension on Main Branch Update

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g vsce

      - name: Login to VS Code Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: vsce login publisher_name -p $VSCE_TOKEN

      - name: Package extension
        run: vsce package

      - name: Publish extension
        run: vsce publish -p $VSCE_TOKEN
